url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/gcash" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

fontawesome: "https://kit.fontawesome.com/9eb6b1689c.js"

# material-icon: "https://fonts.googleapis.com/icon?family=Material+Icons"

google-font: "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap"


swup-animation: "https://unpkg.com/swup@latest/dist/swup.min.js"

sass:
  style: compressed # possible values: nested expanded compact compressed

# external-stylesheet:

stylesheet: main
